microsoft/PSRule.Rules.GitHub

- docs/rules/en/GitHub.Branch.Name.md
- docs/rules/en/GitHub.Repo.CodeOwners.md
- docs/rules/en/GitHub.Repo.Protected.md
- pipeline.build.ps1
- src/PSRule.Rules.GitHub/Common/JsonConverters.cs
- src/PSRule.Rules.GitHub/Data/Models.cs
- src/PSRule.Rules.GitHub/Pipeline/ExportPipeline.cs
- src/PSRule.Rules.GitHub/Pipeline/GitHubClient.cs
- src/PSRule.Rules.GitHub/Pipeline/GitHubContext.cs
- src/PSRule.Rules.GitHub/Pipeline/LoggingExtensions.cs
- src/PSRule.Rules.GitHub/Pipeline/PipelineBuilder.cs
- src/PSRule.Rules.GitHub/en/PSRule-rules.psd1
- src/PSRule.Rules.GitHub/rules/GitHub.Branch.Rule.ps1
- src/PSRule.Rules.GitHub/rules/GitHub.Repo.Rule.ps1
- tests/PSRule.Rules.GitHub.Tests/GitHub.Repo.Tests.ps1
- tests/PSRule.Rules.GitHub.Tests/Resources.Repo.1.json
- General code clean up and fixes.
- Added rule unit tests.
- Added CODEOWNERS rule. #3 
- Updates to rule documentation.
Fixes #5 
- **Rule changes**
> Rule updates and code clean up #5

- CHANGELOG.md
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.psd1
> Minor code clean up

- CHANGELOG.md
> Pre-release v0.1.0-B2009006

- README.md
- Added link to module on PowerShell Gallery.
> Added PowerShell Gallery link

- CONTRIBUTING.md
- README.md
- docs/features.md
- Updated CONTRIBUTING.md.
- Added minor doc corrections and fix links.
> Updated contributing and other minor corrections

- pipeline.build.ps1
- Clean up CI pipeline to use `File` input format for repo scanning.
> Clean up CI pipeline

- .ps-rule/OpenSource.Rule.ps1
- ps-rule.yaml
- src/PSRule.Rules.GitHub/rules/Config.Rule.yaml
- Update rules used to validate repository to support new features in PSRule v0.20.0.
> Update repository rules

- CHANGELOG.md
What's changed since pre-release v0.1.0-B2009006:
- Engineering:
- Bump PSRule dependency to v1.1.0. #41
- See the [change log](https://github.com/microsoft/PSRule/blob/main/docs/CHANGELOG-v1.md#v110)
- Bump Octokit to 0.50.0. #50
- Bump YamlDotNet to 9.1.4. #46
> Pre-release v0.1.0-B2103003

- .github/ISSUE_TEMPLATE/question.md
- CHANGELOG.md
- README.md
- SUPPORT.md
- pipeline.build.ps1
- src/PSRule.Rules.GitHub/Data/Models.cs
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.csproj
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.psd1
- src/PSRule.Rules.GitHub/Pipeline/GitHubClient.cs
- src/PSRule.Rules.GitHub/rules/Baseline.Rule.yaml
- src/PSRule.Rules.GitHub/rules/Config.Rule.yaml
- tests/PSRule.Rules.GitHub.Tests/Resources.Repo.1.json
- General improvements:
- Export pull request reviews branch protection data. #63
- Export additional repository data. #64
- Added resource API versions. #66
- Engineering:
- Bump PSRule dependency to v1.1.0. #67
- Bug fixes:
- Fixed null community profile. #65
Fixes #63 
Fixes #64 
Fixes #65 
Fixes #66 
Fixes #67
- **Other code changes**
> Added export data #63 #64 #65 #66 #67

- .vscode/settings.json
- CHANGELOG.md
- pipeline.build.ps1
- ps-project.yaml
- Bump PSRule dependency to v1.3.0. #70
Fixes #70
> Bump PSRule dependency to v1.3.0 #70

- CHANGELOG.md
What's changed since pre-release v0.1.0-B2104014:
- Engineering:
- Bump PSRule dependency to v1.3.0. #70
> Pre-release v0.1.0-B2105002

- CHANGELOG.md
- README.md
- pipeline.build.ps1
- ps-project.yaml
- src/PSRule.Rules.GitHub/Configuration/PSRuleOption.cs
- src/PSRule.Rules.GitHub/Pipeline/ExportPipeline.cs
- src/PSRule.Rules.GitHub/Pipeline/PipelineBuilder.cs
- src/PSRule.Rules.GitHub/Pipeline/RepositoryHelper.cs
- src/PSRule.Rules.GitHub/Runtime/Helper.cs
- src/PSRule.Rules.GitHub/rules/Config.Rule.yaml
- src/PSRule.Rules.GitHub/rules/Convention.Rule.ps1
- New features:
- Automatically export repository data when running in Github Actions. #80
- Engineering:
- Bump PSRule dependency to v1.7.0. #79
Fixes #80 
Fixes #79
- **Other code changes**
> Added convention for repo export #80

- CHANGELOG.md
What's changed since pre-release v0.1.0-B2105002:
- New features:
- Automatically export repository data when running in Github Actions. #80
- Engineering:
- Bump PSRule dependency to v1.7.0. #79
> Pre-release v0.1.0-B2109006

- .azure-pipelines/jobs/integrationContainer.yaml
- .azure-pipelines/jobs/testContainer.yaml
- Use latest CI image versions.
> Bump CI image versions

- .devcontainer/container-build.ps1
- .devcontainer/container-start.ps1
- .devcontainer/devcontainer.json
- .editorconfig
- .github/workflows/analyze.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/stale.yaml
- .vscode/settings.json
- modules.json
- pipeline.build.ps1
- scripts/dependencies.psm1
- src/PSRule.Rules.GitHub/Common/HttpClientExtensions.cs
- src/PSRule.Rules.GitHub/Common/JsonConverters.cs
- src/PSRule.Rules.GitHub/Pipeline/ExportPipeline.cs
- src/PSRule.Rules.GitHub/Pipeline/GitHubClient.cs
- src/PSRule.Rules.GitHub/Pipeline/GitHubContext.cs
- src/PSRule.Rules.GitHub/Pipeline/LoggingExtensions.cs
- src/PSRule.Rules.GitHub/Pipeline/Output/FileOutputWriter.cs
- src/PSRule.Rules.GitHub/Pipeline/Output/PSPipelineWriter.cs
- src/PSRule.Rules.GitHub/Pipeline/PipelineBuilder.cs
- src/PSRule.Rules.GitHub/Pipeline/PipelineWriter.cs
- src/PSRule.Rules.GitHub/Runtime/Helper.cs
- tests/PSRule.Rules.GitHub.Tests/GitHub.Branch.Tests.ps1
- tests/PSRule.Rules.GitHub.Tests/GitHub.Repo.Tests.ps1
- Added security scanning.
- Added workflow for automatic dependency updates.
- Updated tests for Pester v5.
- Code refactoring and clean up.
- **Other code changes**
> CI improvements and refactoring

- .github/workflows/build.yaml
- pipeline.build.ps1
- src/PSRule.Rules.GitHub/Runtime/Helper.cs
- src/PSRule.Rules.GitHub/rules/Convention.Rule.ps1
- tests/Integration/Cmdlet.Integration.Tests.ps1
> Try self tests

- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.csproj
> Add source link

- CHANGELOG.md
- docs/rules/en/GitHub.Repo.Contributing.md
- docs/rules/en/GitHub.Repo.Description.md
- docs/rules/en/GitHub.Repo.IssueTempate.md
- docs/rules/en/GitHub.Repo.License.md
- docs/rules/en/GitHub.Repo.PRTemplate.md
- src/PSRule.Rules.GitHub/Pipeline/ExportPipeline.cs
- src/PSRule.Rules.GitHub/en/PSRule-rules.psd1
- src/PSRule.Rules.GitHub/rules/GitHub.Repo.Rule.ps1
- tests/PSRule.Rules.GitHub.Tests/GitHub.Repo.Tests.ps1
- tests/PSRule.Rules.GitHub.Tests/Resources.Repo.1.json
- New rules:
- Community files:
- Use recommended community files. #3
- Added checks for license and description.
- Added checks for PR templates.
- Added checks for issue templates.
Fixes #3 
- **Rule changes**
> Added community rule checks #3

- CHANGELOG.md
What's changed since pre-release v0.1.0-B2109006:
- New rules:
- Community files:
- Use recommended community files. #3
- Added checks for license and description.
- Added checks for PR templates.
- Added checks for issue templates.
- Engineering:
- Bump PSRule dependency to v1.11.0. #91
> Pre-release v0.1.0-B2202018

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/integration-pipeline.yaml
- pipeline.build.ps1
- Updates to CI releases process including image versions and force release option.
> Update force release CI option

- CHANGELOG.md
- README.md
What's changed since v0.1.0:
- Engineering:
- Bump PSRule dependency to v2.0.0. #105
> Pre-release v0.2.0-B2204007

- CHANGELOG.md
What's changed since pre-release v0.2.0-B2205009:
- Engineering:
- Bump Newtonsoft.Json to v13.0.1.
[#121](https://github.com/microsoft/PSRule.Rules.GitHub/pull/121)
> Pre-release v0.2.0-B2206003

- README.md
- Fixed command line in docs.
Fixes #128
> Fixed command line in docs #128

- .azure-pipelines/azure-pipelines.yaml
- .vscode/settings.json
- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.csproj
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.psd1
- Update packaging for code signing and SBOM.
Fixes #131
> Update packaging for code signing #131

- README.md
Simply correcting url path for docs
- **Rule changes**
- **Other code changes**
> Fix Link - Rules By Category

- .config/dotnet-tools.json
- .github/dependabot.yml
- .github/workflows/build.yaml
- global.json
- src/PSRule.Rules.GitHub/PSRule.Rules.GitHub.csproj
- src/PSRule.Rules.GitHub/packages.lock.json
- src/SDK/packages.lock.json
- tests/PSRule.Rules.GitHub.Tests/PSRule.Rules.GitHub.Tests.csproj
> Update .NET requirements
